-- Tabla Hotel
CREATE TABLE HOTEL (
    ID_HOTEL        NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE_HOTEL    VARCHAR2(100) NOT NULL,
    DIRECCION       VARCHAR2(150),
    CATEGORIA       VARCHAR2(50),
    CONSTRAINT PK_HOTEL PRIMARY KEY (ID_HOTEL)
);

-- Tabla Habitación
CREATE TABLE HABITACION (
    ID_HABITACION    NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_HOTEL         NUMBER NOT NULL,
    TIPO_HAB         VARCHAR2(50),
    CAPACIDAD        NUMBER(2),
    PRECIO           NUMBER(10) NOT NULL,
    DISPONIBILIDAD   CHAR(1) ,
    CONSTRAINT PK_HABITACION PRIMARY KEY (ID_HABITACION),
    CONSTRAINT FK_HAB_HOTEL FOREIGN KEY (ID_HOTEL)
        REFERENCES HOTEL(ID_HOTEL)
);

-- Tabla Cliente
CREATE TABLE CLIENTE (
    ID_CLIENTE       NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE_CL        VARCHAR2(50) NOT NULL,
    APELLIDO_P_CL    VARCHAR2(50) NOT NULL,
    APELLIDO_M_CL    VARCHAR2(50),
    CORREO           VARCHAR2(100) UNIQUE NOT NULL,
    TELEFONO         VARCHAR2(20) NOT NULL,
    DIRECCION        VARCHAR2(150),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE)
);



-- Tabla Tipo_empleado
CREATE TABLE TIPO_EMPLEADO (
    COD_EMPLEADO    NUMBER GENERATED ALWAYS AS IDENTITY,
    DESCRIPCION     VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_TIPO_EMPLEADO PRIMARY KEY (COD_EMPLEADO)
);

-- Tabla Pago
CREATE TABLE PAGO (
    ID_PAGO       NUMBER GENERATED ALWAYS AS IDENTITY,
    TIPO_PAGO     VARCHAR2(50) NOT NULL,
    ESTADO_PAGO   VARCHAR2(30) NOT NULL,
    FECHA_PAGO    DATE NOT NULL,
    TOTAL_PAGO    NUMBER(10) NOT NULL,
    ABONO         NUMBER(10),
    CONSTRAINT PK_PAGO PRIMARY KEY (ID_PAGO)
);




-- Tabla Empleado
CREATE TABLE EMPLEADO (
    ID_EMPLEADO     NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE_EMP      VARCHAR2(50) NOT NULL,
    APELLIDO_P_EMP  VARCHAR2(50) NOT NULL,
    APELLIDO_M_EMP  VARCHAR2(50),
    ID_HOTEL        NUMBER NOT NULL,
    COD_EMPLEADO    NUMBER NOT NULL,
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID_EMPLEADO),
    CONSTRAINT FK_EMP_HOTEL FOREIGN KEY (ID_HOTEL)
        REFERENCES HOTEL(ID_HOTEL),
    CONSTRAINT FK_EMP_TIPO FOREIGN KEY (COD_EMPLEADO)
        REFERENCES TIPO_EMPLEADO(COD_EMPLEADO)
);


-- Tabla Reserva
CREATE TABLE RESERVA (
    ID_RESERVA         NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_CLIENTE         NUMBER NOT NULL,
    ID_HABITACION      NUMBER NOT NULL,
    ID_PAGO            NUMBER,
    ID_EMPLEADO        NUMBER,
    FECHA_ENTRADA      DATE NOT NULL,
    FECHA_SALIDA       DATE NOT NULL,
    CANTIDAD_PERSONAS  NUMBER(2),
    CONSTRAINT PK_RESERVA PRIMARY KEY (ID_RESERVA),
    CONSTRAINT FK_RES_CLIENTE FOREIGN KEY (ID_CLIENTE)
        REFERENCES CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_RES_HAB FOREIGN KEY (ID_HABITACION)
        REFERENCES HABITACION(ID_HABITACION),
    CONSTRAINT FK_RES_PAGO FOREIGN KEY (ID_PAGO)
        REFERENCES PAGO(ID_PAGO),
    CONSTRAINT FK_RES_EMP FOREIGN KEY (ID_EMPLEADO)
        REFERENCES EMPLEADO(ID_EMPLEADO)
);


-- LIMPIAR BASE
DROP TABLE EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE HOTEL CASCADE CONSTRAINTS;
DROP TABLE HABITACION CASCADE CONSTRAINTS;
DROP TABLE CLIENTE CASCADE CONSTRAINTS;
DROP TABLE TIPO_EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE PAGO CASCADE CONSTRAINTS;
DROP TABLE RESERVA CASCADE CONSTRAINTS;




-- CRUD

-- Prueba de Create (Insert)

-- Insert hotel
INSERT INTO HOTEL (NOMBRE_HOTEL, DIRECCION, CATEGORIA)
VALUES ('Hotel Pacific Reef', 'Av. Providencia 1234, Santiago', '5 estrellas');


-- Insert Cliente

INSERT INTO CLIENTE (NOMBRE_CL, APELLIDO_P_CL, APELLIDO_M_CL, CORREO, TELEFONO, DIRECCION)
VALUES ('Carlos', 'Pérez', 'Gómez', 'carlos.perez@gmail.com', '+56911111111', 'Santiago');



-- Prueba de Read (Select)


SELECT * FROM HOTEL;

SELECT * FROM CLIENTE;

COMMIT;
-- Prueba de Update

-- Actualizar correo de un cliente
UPDATE CLIENTE
SET CORREO = 'carlos.perez123@gmail.com'
WHERE NOMBRE_CL = 'Carlos' AND APELLIDO_P_CL = 'Pérez';


-- Prueba de Delete

-- Eliminar un cliente
DELETE FROM CLIENTE
WHERE NOMBRE_CL = 'Carlos' AND APELLIDO_P_CL = 'Pérez';

DELETE FROM HOTEL
WHERE ID_HOTEL = 2;
